In [2]:
from factfinder.main import Pff
from factfinder.multi import Pool
import os
import pandas as pd
import itertools
from pathlib import Path
from dotenv import load_dotenv

# Load .env environmental variables for local runs
try:
    env_path = f'../../.env'
    load_dotenv(dotenv_path=env_path)
except:
    print('.env file is missing ...')

# Initialize pff instance
acs = Pff(api_key=os.environ['API_KEY'], year = 2018)
decennial = Pff(api_key=os.environ['API_KEY'], year = 2010)

In [3]:
a = '''(SELECT p FROM demo WHERE variable = 'FPop50t54' and geotype='PUMA2010' and geoid=a.puma) as female_50_54,
(SELECT z FROM demo WHERE variable = 'PopU181' and geotype='City2010') as moe_under18_rate_nyc,
(SELECT z FROM demo WHERE variable = 'PopU181' and geotype='Boro2010' and geoid=a.borocode) as moe_under18_rate_boro,
(SELECT e FROM demo WHERE variable = 'Pop_1' and geotype='PUMA2010' and geoid=a.puma) as pop_acs, 
(SELECT e FROM demo WHERE variable = 'Pop_1' and geotype='Boro2010' and geoid=a.borocode) as pop_acs_boro,
(SELECT e FROM demo WHERE variable = 'Pop_1' and geotype='City2010') as pop_acs_nyc,  
(SELECT p FROM demo WHERE variable = 'Hsp1' and geotype='PUMA2010' and geoid=a.puma) as pct_hispanic,
(SELECT p FROM demo WHERE variable = 'AsnNH' and geotype='PUMA2010' and geoid=a.puma) as pct_asian_nh,
(SELECT p FROM demo WHERE variable = 'BlNH' and geotype='PUMA2010' and geoid=a.puma) as pct_black_nh,
(SELECT p FROM demo WHERE variable = 'WtNH' and geotype='PUMA2010' and geoid=a.puma) as pct_white_nh,
(SELECT p FROM demo WHERE variable = 'FPop85pl' and geotype='PUMA2010' and geoid=a.puma) as female_85_over,
(SELECT p FROM demo WHERE variable = 'MPop85pl' and geotype='PUMA2010' and geoid=a.puma) as male_85_over,
(SELECT p FROM demo WHERE variable = 'FPop80t84' and geotype='PUMA2010' and geoid=a.puma) as female_80_84,
(SELECT p FROM demo WHERE variable = 'MPop80t84' and geotype='PUMA2010' and geoid=a.puma) as male_80_84,
(SELECT p FROM demo WHERE variable = 'FPop75t79' and geotype='PUMA2010' and geoid=a.puma) as female_75_79,
(SELECT p FROM demo WHERE variable = 'MPop75t79' and geotype='PUMA2010' and geoid=a.puma) as male_75_79,
(SELECT p FROM demo WHERE variable = 'FPop70t74' and geotype='PUMA2010' and geoid=a.puma) as female_70_74,
(SELECT p FROM demo WHERE variable = 'MPop70t74' and geotype='PUMA2010' and geoid=a.puma) as male_70_74,
(SELECT p FROM demo WHERE variable = 'FPop65t69' and geotype='PUMA2010' and geoid=a.puma) as female_65_69,
(SELECT p FROM demo WHERE variable = 'MPop65t69' and geotype='PUMA2010' and geoid=a.puma) as male_65_69,
(SELECT p FROM demo WHERE variable = 'FPop60t64' and geotype='PUMA2010' and geoid=a.puma) as female_60_64,
(SELECT p FROM demo WHERE variable = 'MPop60t64' and geotype='PUMA2010' and geoid=a.puma) as male_60_64,
(SELECT p FROM demo WHERE variable = 'FPop55t59' and geotype='PUMA2010' and geoid=a.puma) as female_55_59,
(SELECT p FROM demo WHERE variable = 'MPop55t59' and geotype='PUMA2010' and geoid=a.puma) as male_55_59,
(SELECT p FROM demo WHERE variable = 'MPop50t54' and geotype='PUMA2010' and geoid=a.puma) as male_50_54,
(SELECT p FROM demo WHERE variable = 'FPop45t49' and geotype='PUMA2010' and geoid=a.puma) as female_45_49,
(SELECT p FROM demo WHERE variable = 'MPop45t49' and geotype='PUMA2010' and geoid=a.puma) as male_45_49,
(SELECT p FROM demo WHERE variable = 'FPop40t44' and geotype='PUMA2010' and geoid=a.puma) as female_40_44,
(SELECT p FROM demo WHERE variable = 'MPop40t44' and geotype='PUMA2010' and geoid=a.puma) as male_40_44,
(SELECT p FROM demo WHERE variable = 'FPop35t39' and geotype='PUMA2010' and geoid=a.puma) as female_35_39,
(SELECT p FROM demo WHERE variable = 'MPop35t39' and geotype='PUMA2010' and geoid=a.puma) as male_35_39,
(SELECT p FROM demo WHERE variable = 'FPop30t34' and geotype='PUMA2010' and geoid=a.puma) as female_30_34,
(SELECT p FROM demo WHERE variable = 'MPop30t34' and geotype='PUMA2010' and geoid=a.puma) as male_30_34,
(SELECT p FROM demo WHERE variable = 'FPop25t29' and geotype='PUMA2010' and geoid=a.puma) as female_25_29,
(SELECT p FROM demo WHERE variable = 'MPop25t29' and geotype='PUMA2010' and geoid=a.puma) as male_25_29,
(SELECT p FROM demo WHERE variable = 'FPop20t24' and geotype='PUMA2010' and geoid=a.puma) as female_20_24,
(SELECT p FROM demo WHERE variable = 'MPop20t24' and geotype='PUMA2010' and geoid=a.puma) as male_20_24,
(SELECT p FROM demo WHERE variable = 'FPop15t19' and geotype='PUMA2010' and geoid=a.puma) as female_15_19,
(SELECT p FROM demo WHERE variable = 'MPop15t19' and geotype='PUMA2010' and geoid=a.puma) as male_15_19,
(SELECT p FROM demo WHERE variable = 'FPop10t14' and geotype='PUMA2010' and geoid=a.puma) as female_10_14,
(SELECT p FROM demo WHERE variable = 'MPop10t14' and geotype='PUMA2010' and geoid=a.puma) as male_10_14,
(SELECT p FROM demo WHERE variable = 'FPop5t9' and geotype='PUMA2010' and geoid=a.puma) as female_5_9,
(SELECT p FROM demo WHERE variable = 'MPop5t9' and geotype='PUMA2010' and geoid=a.puma) as male_5_9,
(SELECT p FROM demo WHERE variable = 'FPop0t5' and geotype='PUMA2010' and geoid=a.puma) as female_under_5,
(SELECT p FROM demo WHERE variable = 'MPop0t5' and geotype='PUMA2010' and geoid=a.puma) as male_under_5,
(SELECT z FROM demo WHERE variable = 'Pop65pl1' and geotype='City2010') as moe_over65_rate_nyc,
(SELECT p FROM demo WHERE variable = 'Pop65pl1' and geotype='City2010') as over65_rate_nyc,
(SELECT z FROM demo WHERE variable = 'Pop65pl1' and geotype='Boro2010' and geoid=a.borocode) as moe_over65_rate_boro,
(SELECT p FROM demo WHERE variable = 'Pop65pl1' and geotype='Boro2010' and geoid=a.borocode) as over65_rate_boro,
(SELECT z FROM demo WHERE variable = 'Pop65pl1' and geotype='PUMA2010' and geoid=a.puma) as moe_over65_rate,
(SELECT p FROM demo WHERE variable = 'Pop65pl1' and geotype='PUMA2010' and geoid=a.puma) as over65_rate,
(SELECT p FROM demo WHERE variable = 'PopU181' and geotype='City2010') as under18_rate_nyc,
(SELECT p FROM demo WHERE variable = 'PopU181' and geotype='Boro2010' and geoid=a.borocode) as under18_rate_boro,
(SELECT z FROM demo WHERE variable = 'PopU181' and geotype='PUMA2010' and geoid=a.puma) as moe_under18_rate,
(SELECT p FROM demo WHERE variable = 'PopU181' and geotype='PUMA2010' and geoid=a.puma) as under18_rate,
(SELECT z FROM soci WHERE variable = 'LgOEnLEP1' and geotype='City2010') as moe_lep_rate_nyc,
(SELECT p FROM soci WHERE variable = 'LgOEnLEP1' and geotype='City2010') as lep_rate_nyc,
(SELECT z FROM soci WHERE variable = 'LgOEnLEP1' and geotype='Boro2010' and geoid=a.borocode) as moe_lep_rate_boro,
(SELECT p FROM soci WHERE variable = 'LgOEnLEP1' and geotype='Boro2010' and geoid=a.borocode) as lep_rate_boro,
(SELECT z FROM soci WHERE variable = 'LgOEnLEP1' and geotype='PUMA2010' and geoid=a.puma) as moe_lep_rate,
(SELECT p FROM soci WHERE variable = 'LgOEnLEP1' and geotype='PUMA2010' and geoid=a.puma) as lep_rate,
(SELECT z FROM soci WHERE variable = 'Fb1' and geotype='PUMA2010' and geoid=a.puma) as moe_foreign_born,
(SELECT p FROM soci WHERE variable = 'Fb1' and geotype='PUMA2010' and geoid=a.puma) as pct_foreign_born,
(SELECT z FROM hous WHERE variable = 'GRPI35pl' and geotype='City2010') as moe_hh_rent_burd_nyc,
(SELECT p FROM hous WHERE variable = 'GRPI35pl' and geotype='City2010') as pct_hh_rent_burd_nyc,
(SELECT z FROM hous WHERE variable = 'GRPI35pl' and geotype='Boro2010' and geoid=a.borocode) as moe_hh_rent_burd_boro,
(SELECT p FROM hous WHERE variable = 'GRPI35pl' and geotype='Boro2010' and geoid=a.borocode) as pct_hh_rent_burd_boro,
(SELECT z FROM hous WHERE variable = 'GRPI35pl' and geotype='PUMA2010' and geoid=a.puma) as moe_hh_rent_burd,
(SELECT p FROM hous WHERE variable = 'GRPI35pl' and geotype='PUMA2010' and geoid=a.puma) as pct_hh_rent_burd,
(SELECT m FROM econ WHERE variable = 'MnTrvTm' and geotype='City2010') as moe_mean_commute_nyc,
(SELECT e FROM econ WHERE variable = 'MnTrvTm' and geotype='City2010') as mean_commute_nyc,
(SELECT m FROM econ WHERE variable = 'MnTrvTm' and geotype='Boro2010' and geoid=a.borocode) as moe_mean_commute_boro,
(SELECT e FROM econ WHERE variable = 'MnTrvTm' and geotype='Boro2010' and geoid=a.borocode) as mean_commute_boro,
(SELECT m FROM econ WHERE variable = 'MnTrvTm' and geotype='PUMA2010' and geoid=a.puma) as moe_mean_commute,
(SELECT e FROM econ WHERE variable = 'MnTrvTm' and geotype='PUMA2010' and geoid=a.puma) as mean_commute,
(SELECT z FROM econ WHERE variable = 'CvLFUEm1' and geotype='City2010') as moe_unemployment_nyc,
(SELECT p FROM econ WHERE variable = 'CvLFUEm1' and geotype='City2010') as unemployment_nyc,
(SELECT z FROM econ WHERE variable = 'CvLFUEm1' and geotype='Boro2010' and geoid=a.borocode) as moe_unemployment_boro,
(SELECT p FROM econ WHERE variable = 'CvLFUEm1' and geotype='Boro2010' and geoid=a.borocode) as unemployment_boro,
(SELECT z FROM econ WHERE variable = 'CvLFUEm1' and geotype='PUMA2010' and geoid=a.puma) as moe_unemployment,
(SELECT p FROM econ WHERE variable = 'CvLFUEm1' and geotype='PUMA2010' and geoid=a.puma) as unemployment,
(SELECT z FROM soci WHERE variable = 'EA_BchDH' and geotype='City2010') as moe_bach_deg_nyc,
(SELECT p FROM soci WHERE variable = 'EA_BchDH' and geotype='City2010') as pct_bach_deg_nyc,
(SELECT z FROM soci WHERE variable = 'EA_BchDH' and geotype='Boro2010' and geoid=a.borocode) as moe_bach_deg_boro,
(SELECT p FROM soci WHERE variable = 'EA_BchDH' and geotype='Boro2010' and geoid=a.borocode) as pct_bach_deg_boro,
(SELECT z FROM soci WHERE variable = 'EA_BchDH' and geotype='PUMA2010' and geoid=a.puma) as moe_bach_deg,
(SELECT p FROM soci WHERE variable = 'EA_BchDH' and geotype='PUMA2010' and geoid=a.puma) as pct_bach_deg'''

In [4]:
variable_mapping = []
for i in a.split(','):
    i = i.strip().replace('\n', '')
    var_type = i[8:10].strip()
    pff_variable = i[38:].split("'")[0].strip().lower()
    geotype=i[38:].split("and geotype='")[1].split("'")[0].strip().lower()
    target=i[38:].split('as')[1].strip()
    variable_mapping.append(
        dict(
             var_type=var_type, 
             pff_variable=pff_variable, 
             geotype=geotype, 
             target=target
        ))

In [5]:
df= pd.DataFrame(variable_mapping)

In [6]:
df

   var_type pff_variable   geotype                 target
0         p    fpop50t54  puma2010           female_50_54
1         z      popu181  city2010   moe_under18_rate_nyc
2         z      popu181  boro2010  moe_under18_rate_boro
3         e        pop_1  puma2010                pop_acs
4         e        pop_1  boro2010           pop_acs_boro
..      ...          ...       ...                    ...
82        p     ea_bchdh  city2010       pct_bach_deg_nyc
83        z     ea_bchdh  boro2010      moe_bach_deg_boro
84        p     ea_bchdh  boro2010      pct_bach_deg_boro
85        z     ea_bchdh  puma2010           moe_bach_deg
86        p     ea_bchdh  puma2010           pct_bach_deg

[87 rows x 4 columns]

In [7]:
df['column_mapping'] = df.apply(lambda x: {x['var_type']:x['target']}, axis=1)
geotype_translate = {
    'puma2010':'cd',
    'city2010': 'city',
    'boro2010': 'borough'
}
df['geotype'] = df.apply(lambda x: geotype_translate.get(x['geotype']), axis=1)

In [8]:
def agg(df):
    out={}
    for i in df['column_mapping'].to_list():
        out.update(i)
    return out
dff = df.groupby(['pff_variable', 'geotype']).apply(agg)

In [9]:
dff.reset_index().rename(columns={0:"column_mapping"}).to_dict('records')

[{'pff_variable': 'asnnh', 'geotype': 'cd', 'column_mapping': {'p': 'pct_'}},
 {'pff_variable': 'blnh',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_black_nh'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_unemployment_boro', 'p': 'unemployment_boro'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_unemployment', 'p': 'unemployment'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_unemployment_nyc', 'p': 'unemployment_nyc'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_bach_deg_boro', 'p': 'pct_bach_deg_boro'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_bach_deg', 'p': 'pct_bach_deg'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_bach_deg_nyc', 'p': 'pct_bach_deg_nyc'}},
 {'pff_variable': 'fb1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_foreign_born', 'p': 'pct_foreign_born'}},
 {'pff_variable': 'fpop0t5',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_under_5'}},
 {'pff_variable': 'fpop10t14',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_10_14'}},
 {'pff_variable': 'fpop15t19',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_15_19'}},
 {'pff_variable': 'fpop20t24',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_20_24'}},
 {'pff_variable': 'fpop25t29',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_25_29'}},
 {'pff_variable': 'fpop30t34',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_30_34'}},
 {'pff_variable': 'fpop35t39',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_35_39'}},
 {'pff_variable': 'fpop40t44',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_40_44'}},
 {'pff_variable': 'fpop45t49',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_45_49'}},
 {'pff_variable': 'fpop50t54',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_50_54'}},
 {'pff_variable': 'fpop55t59',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_55_59'}},
 {'pff_variable': 'fpop5t9',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_5_9'}},
 {'pff_variable': 'fpop60t64',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_60_64'}},
 {'pff_variable': 'fpop65t69',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_65_69'}},
 {'pff_variable': 'fpop70t74',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_70_74'}},
 {'pff_variable': 'fpop75t79',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_75_79'}},
 {'pff_variable': 'fpop80t84',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_80_84'}},
 {'pff_variable': 'fpop85pl',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_85_over'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_hh_rent_burd_boro',
   'p': 'pct_hh_rent_burd_boro'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_hh_rent_burd', 'p': 'pct_hh_rent_burd'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_hh_rent_burd_nyc',
   'p': 'pct_hh_rent_burd_nyc'}},
 {'pff_variable': 'hsp1',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_hispanic'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_lep_rate_boro', 'p': 'lep_rate_boro'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_lep_rate', 'p': 'lep_rate'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_lep_rate_nyc', 'p': 'lep_rate_nyc'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'borough',
  'column_mapping': {'m': 'moe_mean_commute_boro', 'e': 'mean_commute_boro'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'cd',
  'column_mapping': {'m': 'moe_mean_commute', 'e': 'mean_commute'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'city',
  'column_mapping': {'m': 'moe_mean_commute_nyc', 'e': 'mean_commute_nyc'}},
 {'pff_variable': 'mpop0t5',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_under_5'}},
 {'pff_variable': 'mpop10t14',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_10_14'}},
 {'pff_variable': 'mpop15t19',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_15_19'}},
 {'pff_variable': 'mpop20t24',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_20_24'}},
 {'pff_variable': 'mpop25t29',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_25_29'}},
 {'pff_variable': 'mpop30t34',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_30_34'}},
 {'pff_variable': 'mpop35t39',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_35_39'}},
 {'pff_variable': 'mpop40t44',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_40_44'}},
 {'pff_variable': 'mpop45t49',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_45_49'}},
 {'pff_variable': 'mpop50t54',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_50_54'}},
 {'pff_variable': 'mpop55t59',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_55_59'}},
 {'pff_variable': 'mpop5t9',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_5_9'}},
 {'pff_variable': 'mpop60t64',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_60_64'}},
 {'pff_variable': 'mpop65t69',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_65_69'}},
 {'pff_variable': 'mpop70t74',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_70_74'}},
 {'pff_variable': 'mpop75t79',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_75_79'}},
 {'pff_variable': 'mpop80t84',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_80_84'}},
 {'pff_variable': 'mpop85pl',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_85_over'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_over65_rate_boro', 'p': 'over65_rate_boro'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_over65_rate', 'p': 'over65_rate'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_over65_rate_nyc', 'p': 'over65_rate_nyc'}},
 {'pff_variable': 'pop_1',
  'geotype': 'borough',
  'column_mapping': {'e': 'pop_acs_boro'}},
 {'pff_variable': 'pop_1',
  'geotype': 'cd',
  'column_mapping': {'e': 'pop_acs'}},
 {'pff_variable': 'pop_1',
  'geotype': 'city',
  'column_mapping': {'e': 'pop_acs_nyc'}},
 {'pff_variable': 'popu181',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_under18_rate_boro', 'p': 'under18_rate_boro'}},
 {'pff_variable': 'popu181',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_under18_rate', 'p': 'under18_rate'}},
 {'pff_variable': 'popu181',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_under18_rate_nyc', 'p': 'under18_rate_nyc'}},
 {'pff_variable': 'wtnh',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_white_nh'}}]

In [10]:
variable_mapping=[{'pff_variable': 'asnnh', 'geotype': 'cd', 'column_mapping': {'p': 'pct_'}},
 {'pff_variable': 'blnh',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_black_nh'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_unemployment_boro', 'p': 'unemployment_boro'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_unemployment', 'p': 'unemployment'}},
 {'pff_variable': 'cvlfuem1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_unemployment_nyc', 'p': 'unemployment_nyc'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_bach_deg_boro', 'p': 'pct_bach_deg_boro'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_bach_deg', 'p': 'pct_bach_deg'}},
 {'pff_variable': 'ea_bchdh',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_bach_deg_nyc', 'p': 'pct_bach_deg_nyc'}},
 {'pff_variable': 'fb1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_foreign_born', 'p': 'pct_foreign_born'}},
 {'pff_variable': 'fpop0t5',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_under_5'}},
 {'pff_variable': 'fpop10t14',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_10_14'}},
 {'pff_variable': 'fpop15t19',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_15_19'}},
 {'pff_variable': 'fpop20t24',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_20_24'}},
 {'pff_variable': 'fpop25t29',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_25_29'}},
 {'pff_variable': 'fpop30t34',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_30_34'}},
 {'pff_variable': 'fpop35t39',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_35_39'}},
 {'pff_variable': 'fpop40t44',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_40_44'}},
 {'pff_variable': 'fpop45t49',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_45_49'}},
 {'pff_variable': 'fpop50t54',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_50_54'}},
 {'pff_variable': 'fpop55t59',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_55_59'}},
 {'pff_variable': 'fpop5t9',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_5_9'}},
 {'pff_variable': 'fpop60t64',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_60_64'}},
 {'pff_variable': 'fpop65t69',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_65_69'}},
 {'pff_variable': 'fpop70t74',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_70_74'}},
 {'pff_variable': 'fpop75t79',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_75_79'}},
 {'pff_variable': 'fpop80t84',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_80_84'}},
 {'pff_variable': 'fpop85pl',
  'geotype': 'cd',
  'column_mapping': {'p': 'female_85_over'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_hh_rent_burd_boro',
   'p': 'pct_hh_rent_burd_boro'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_hh_rent_burd', 'p': 'pct_hh_rent_burd'}},
 {'pff_variable': 'grpi35pl',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_hh_rent_burd_nyc',
   'p': 'pct_hh_rent_burd_nyc'}},
 {'pff_variable': 'hsp1',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_hispanic'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_lep_rate_boro', 'p': 'lep_rate_boro'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_lep_rate', 'p': 'lep_rate'}},
 {'pff_variable': 'lgoenlep1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_lep_rate_nyc', 'p': 'lep_rate_nyc'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'borough',
  'column_mapping': {'m': 'moe_mean_commute_boro', 'e': 'mean_commute_boro'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'cd',
  'column_mapping': {'m': 'moe_mean_commute', 'e': 'mean_commute'}},
 {'pff_variable': 'mntrvtm',
  'geotype': 'city',
  'column_mapping': {'m': 'moe_mean_commute_nyc', 'e': 'mean_commute_nyc'}},
 {'pff_variable': 'mpop0t5',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_under_5'}},
 {'pff_variable': 'mpop10t14',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_10_14'}},
 {'pff_variable': 'mpop15t19',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_15_19'}},
 {'pff_variable': 'mpop20t24',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_20_24'}},
 {'pff_variable': 'mpop25t29',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_25_29'}},
 {'pff_variable': 'mpop30t34',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_30_34'}},
 {'pff_variable': 'mpop35t39',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_35_39'}},
 {'pff_variable': 'mpop40t44',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_40_44'}},
 {'pff_variable': 'mpop45t49',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_45_49'}},
 {'pff_variable': 'mpop50t54',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_50_54'}},
 {'pff_variable': 'mpop55t59',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_55_59'}},
 {'pff_variable': 'mpop5t9',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_5_9'}},
 {'pff_variable': 'mpop60t64',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_60_64'}},
 {'pff_variable': 'mpop65t69',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_65_69'}},
 {'pff_variable': 'mpop70t74',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_70_74'}},
 {'pff_variable': 'mpop75t79',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_75_79'}},
 {'pff_variable': 'mpop80t84',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_80_84'}},
 {'pff_variable': 'mpop85pl',
  'geotype': 'cd',
  'column_mapping': {'p': 'male_85_over'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_over65_rate_boro', 'p': 'over65_rate_boro'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_over65_rate', 'p': 'over65_rate'}},
 {'pff_variable': 'pop65pl1',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_over65_rate_nyc', 'p': 'over65_rate_nyc'}},
 {'pff_variable': 'pop_1',
  'geotype': 'borough',
  'column_mapping': {'e': 'pop_acs_boro'}},
 {'pff_variable': 'pop_1',
  'geotype': 'cd',
  'column_mapping': {'e': 'pop_acs'}},
 {'pff_variable': 'pop_1',
  'geotype': 'city',
  'column_mapping': {'e': 'pop_acs_nyc'}},
 {'pff_variable': 'popu181',
  'geotype': 'borough',
  'column_mapping': {'z': 'moe_under18_rate_boro', 'p': 'under18_rate_boro'}},
 {'pff_variable': 'popu181',
  'geotype': 'cd',
  'column_mapping': {'z': 'moe_under18_rate', 'p': 'under18_rate'}},
 {'pff_variable': 'popu181',
  'geotype': 'city',
  'column_mapping': {'z': 'moe_under18_rate_nyc', 'p': 'under18_rate_nyc'}},
 {'pff_variable': 'wtnh',
  'geotype': 'cd',
  'column_mapping': {'p': 'pct_white_nh'}}]

In [11]:
def calculate(inputs):
    pff_variable=inputs['pff_variable']
    geotype=inputs['geotype']
    column_mapping=inputs['column_mapping']
    return acs.calculate(pff_variable,geotype).rename(columns=column_mapping)[['census_geoid']+list(column_mapping.values())]

In [12]:
dfs = []
for i in variable_mapping:
    tmp = calculate(i)
    print(tmp.head())
# dff = pd.concat(dfs)

census_geoid  pct_
0          101  20.9
1          102  14.1
2          103  30.6
3          104  16.7
4          105  19.2
  census_geoid  pct_black_nh
0          101           3.2
1          102           1.9
2          103           8.4
3          104           6.3
4          105           3.3
  census_geoid  moe_unemployment_boro  unemployment_boro
0        36005                    0.2                6.3
0        36081                    0.1                4.0
0        36085                    0.2                2.8
0        36047                    0.1                4.4
0        36061                    0.1                3.8
  census_geoid  moe_unemployment  unemployment
0          101               0.5           2.7
1          102               0.5           2.9
2          103               0.4           3.6
3          104               0.6           3.6
4          105               0.6           3.2
  census_geoid  moe_unemployment_nyc  unemployment_nyc
0      3651000                   0.1               4.4
  census_geoid  moe_bach_deg_boro  pct_bach_deg_boro
0        36005                0.3               19.8
0        36081                0.3               31.5
0        36085                0.7               33.0
0        36047                0.3               36.5
0        36061                0.4               60.8
  census_geoid  moe_bach_deg  pct_bach_deg
0          101           1.2          78.8
1          102           1.4          80.4
2          103           1.2          43.3
3          104           1.4          71.2
4          105           1.4          82.3
  census_geoid  moe_bach_deg_nyc  pct_bach_deg_nyc
0      3651000               0.2              37.4
  census_geoid  moe_foreign_born  pct_foreign_born
0          101               1.5              28.1
1          102               1.3              21.5
2          103               1.1              34.5
3          104               1.5              31.8
4          105               1.4              26.4
  census_geoid  female_under_5
0          101             3.6
1          102             1.9
2          103             1.5
3          104             2.0
4          105             1.9
  census_geoid  female_10_14
0          101           1.4
1          102           0.8
2          103           1.5
3          104           1.0
4          105           0.8
  census_geoid  female_15_19
0          101           1.7
1          102           2.8
2          103           2.9
3          104           1.1
4          105           3.1
  census_geoid  female_20_24
0          101           3.9
1          102           3.7
2          103           4.2
3          104           3.9
4          105           4.9
  census_geoid  female_25_29
0          101           6.3
1          102           7.7
2          103           6.4
3          104           6.7
4          105           8.3
  census_geoid  female_30_34
0          101           6.6
1          102           6.1
2          103           4.1
3          104           6.8
4          105           6.2
  census_geoid  female_35_39
0          101           5.3
1          102           4.0
2          103           3.2
3          104           3.9
4          105           4.5
  census_geoid  female_40_44
0          101           4.2
1          102           2.9
2          103           3.0
3          104           3.0
4          105           2.9
  census_geoid  female_45_49
0          101           3.3
1          102           2.5
2          103           3.2
3          104           2.9
4          105           2.5
  census_geoid  female_50_54
0          101           2.4
1          102           2.3
2          103           2.8
3          104           2.2
4          105           2.8
  census_geoid  female_55_59
0          101           2.3
1          102           2.7
2          103           3.3
3          104           2.9
4          105           3.1
  census_geoid  female_5_9
0          101         2.2
1          102         1.5
2          103         1.2
3          104         0.9
4          105         1.3
  census_geoid  female_60_64
0          101           2.3
1          102           2.9
2          103           3.4
3          104           2.9
4          105           2.5
  census_geoid  female_65_69
0          101           1.7
1          102           2.9
2          103           2.9
3          104           2.3
4          105           2.0
  census_geoid  female_70_74
0          101           1.3
1          102           2.2
2          103           2.1
3          104           2.3
4          105           1.6
  census_geoid  female_75_79
0          101           0.6
1          102           1.4
2          103           1.6
3          104           1.8
4          105           1.1
  census_geoid  female_80_84
0          101           0.7
1          102           1.0
2          103           1.6
3          104           0.6
4          105           0.9
  census_geoid  female_85_over
0          101             1.1
1          102             1.6
2          103             2.1
3          104             1.1
4          105             1.1
  census_geoid  moe_hh_rent_burd_boro  pct_hh_rent_burd_boro
0        36005                    0.6                   50.9
0        36081                    0.5                   46.2
0        36085                    1.7                   46.5
0        36047                    0.4                   45.4
0        36061                    0.5                   36.4
  census_geoid  moe_hh_rent_burd  pct_hh_rent_burd
0          101               2.2              28.4
1          102               2.2              33.4
2          103               1.8              38.4
3          104               2.1              33.6
4          105               2.3              33.2
  census_geoid  moe_hh_rent_burd_nyc  pct_hh_rent_burd_nyc
0      3651000                   0.3                  44.2
  census_geoid  pct_hispanic
0          101           7.0
1          102           6.3
2          103          25.1
3          104          18.8
4          105           7.3

IndexError: list index out of range

In [ ]:
dff.head()